using UnityEngine;
//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------
namespace Urchin.JSON
{
    #pragma warning disable // Disable all warnings
    
    public struct CameraData
    {
        
        public float Id { get; set; }
        
        public string Type { get; set; }
        
        public Vector3 Position { get; set; }
        
        public Vector3 Rotation { get; set; }
        
        public Vector3 Target { get; set; }
        
        public float Zoom { get; set; }
        
        public Vector2 Pan { get; set; }
        
        
        public CameraDataMode Mode { get; set; }
        
        public bool Controllable { get; set; }
        
        public bool Main { get; set; }
    }
    
    
    
    
    
    
    
    
    
    public enum CameraDataMode
    {
        
        Orthographic = 0,
        
        Perspective = 1,
    }
}