using UnityEngine;
//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------
namespace Urchin.JSON
{
    #pragma warning disable // Disable all warnings
    
    public struct NeuronData
    {
        
        public float Id { get; set; }
        
        public string Type { get; set; }
        
        public Vector3 Position { get; set; }
        
        public string Color { get; set; }
        
        public string Shape { get; set; }
        
        public string Material { get; set; }
    }
    
    
}